name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - uses: purescript-contrib/setup-purescript@main
      - uses: srghma/setup-purescript@main

      - name: Install esbuild
        run: npm install

      - name: Build source
        run: spago build

      - name: Run tests
        run: npm run test
